---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - file:
     path: "{{ lookup('env','HOME') }}/sandbox/from_AWX"
     state: directory
     mode: 0755
